### ISSUE TITLE
unable to build on windows 10, qt 5.7 and VS 2015

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera-desktop#1]
I cloned the repo with git clone --recursive

then I opened the project and tried to build it with MSVS compiler

![vlc errrs](https://cloud.githubusercontent.com/assets/1247629/16698323/6fa1e31e-4556-11e6-834a-9f97c6a8bfef.png)

**Comment by RSATom** [comment]
hm... it can't libvlc functions... Do you build it as x64 or x86 application?

**Comment by RSATom** [comment]
please check if you installed 32bit Qt

**Comment by Ivshti** [comment]
Well, that explains it :) 

I didn't. Somehow I thought I should build 64bit

Will check & confirm

**Comment by Ivshti** [comment]
got a more useful stack trace

Smells to me like IPC that's handling texture sending does not like us :) 


[qtwebengine stack trace.txt](https://github.com/RSATom/WebChimera-desktop/files/355482/qtwebengine.stack.trace.txt)

**Comment by Ivshti** [comment]
Seems like 32 bit Qt fixes the issue

Can you write up build instructions or something very explicit that says 32 bit Qt should be used - for people who would try to build from now on :)

**Comment by RSATom** [comment]
I just always mentioned for windows better use 32 bit VLC. Sorry forget mention it here.
