### ISSUE TITLE
webengine build crashes on windows [ONLY IN PARALLELS]

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera-desktop#2]
I'm opening an issue for this so we can track it.

the interesting part is that this just happened to me, the same problem, on a FRESH windows 10 VM with the webengine EXAMPLE and I'm starting to suspect parallels (my vm software) 

Anyway, here's screenshots:
![screen shot 2016-07-09 at 01 01 40](https://cloud.githubusercontent.com/assets/1247629/16702771/e8e60664-4570-11e6-8e0b-b50bbe560dda.png)

The funny thing is that when I tried to debug it, visual Studio also froze...

**Comment by Ivshti** [comment]
![screen shot 2016-07-09 at 01 15 03](https://cloud.githubusercontent.com/assets/1247629/16702996/99057f4c-4572-11e6-9ba4-a862288f4bc8.png)

![screen shot 2016-07-09 at 01 16 07](https://cloud.githubusercontent.com/assets/1247629/16703010/bbd1e4ac-4572-11e6-8d25-1c96d7542f97.png)

This is the best I could do, I realize it's not very useful. Couldn't find debug symbols

Will test on a real device ASAP

**Comment by Ivshti** [comment]
Seems this happens only on parallels

Here's on a real machine
![screenshot-2](https://cloud.githubusercontent.com/assets/1247629/16703688/459aa96c-4578-11e6-9836-d43218317a94.png)
(stremio on top, vlc with big buck bunny on bottom)

The question still would remain what's the problem with parallels; chromium, electron, generic cef - all are ok with parallels

**Comment by RSATom** [comment]
Just use VirtualBox - it doesn't have such problems :)

**Comment by Ivshti** [comment]
If you see what parallels can do you'll redact that statement. It's like running windows natively :)

**Comment by RSATom** [comment]
Is it free to use?

**Comment by Ivshti** [comment]
No :)

**Comment by Ivshti** [comment]
Got a more useful stack trace

It seems like sending textures through the IPC isn't good

[qtwebengine stack trace.txt](https://github.com/RSATom/WebChimera-desktop/files/355486/qtwebengine.stack.trace.txt)

**Comment by RSATom** [comment]
Anyway it's something inside QtWebEngine. Don't think it's relative to `WebChimera-desktop` itself.

**Comment by Ivshti** [comment]
Definitely, I agree - obviously the same issue happens in the webengine samples, but we should follow-up on that. Things like that could be symptoms to problems that can appear on other GPUs besides the parallels virtual GPU
